name: CI

on:
  push:
    branches-ignore:
      - "feature/*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
          cache-dependency-path: yarn.lock
      - run: yarn workspaces focus
        working-directory: packages/core
      - name: Run type check
        run: yarn tsc --noEmit
        working-directory: packages/core
      - name: Run vitest
        run: yarn vitest
        working-directory: packages/core
